FROM alpine

ENV HELM_VERSION="v2.9.1"

RUN apk add --update ca-certificates \
 && apk add --update -t deps curl \
 && curl -L https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz -o /tmp/helm.tgz \
 && tar -zxvf /tmp/helm.tgz -C /tmp \
 && mv /tmp/linux-amd64/helm /usr/bin/helm \
 && rm -rf /tmp/helm.tgz /tmp/linux-amd64 \
 && chmod +x /usr/bin/helm \
 && apk del --purge deps \
 && rm /var/cache/apk/*

ENTRYPOINT ["helm"]
CMD ["help"]
