FROM alpine as builder
ARG KUBE_VERSION=v1.16.3
RUN set -x              && \
apk --update upgrade    && \
apk add ca-certificates bash bash-completion && \
rm -rf /var/cache/apk/* && \
wget -O /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl && \
chmod +x /usr/bin/kubectl && \
mkdir /etc/bash_completion.d && \
/usr/bin/kubectl completion bash >/etc/bash_completion.d/kubectl

ENTRYPOINT ["/usr/bin/kubectl"]
